# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance
    inputs:
      alertWarningLevel: Low
      failOnAlert: true
      scanType: Register
      verbosity: Verbose
