# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ComponentGovernance
    displayName: Component Governance
    jobs:
      - job: ComponentGovernance
        displayName: Component Governance
        steps:
          - task: ComponentGovernanceComponentDetection@0
            displayName: Component Governance
            inputs:
              alertWarningLevel: Low
              failOnAlert: true
              scanType: Register
              verbosity: Verbose
