# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

parameters:
  - name: repositoryName
    type: string
  - name: repositoryRef
    type: string
  - name: templatePath
    type: string
  - name: testInstance
    type: boolean

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: ${{ parameters.repositoryName }}
      ref: ${{ parameters.repositoryRef }}

extends:
  template: ${{ parameters.templatePath }}@PipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        os: windows
        image: windows-latest
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.github/azure-devops/CredScanSuppressions.json
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: "@typescript-eslint/parser"
        parserOptions: ecmaVersion:2018
        enableExclusions: true
        exclusionPatterns: "*.js"
    stages:
      - template: template.yml
        parameters:
          testInstance: ${{ parameters.testInstance }}
