# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: OE/1ESPipelineTemplates
      ref: refs/heads/main

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        os: windows
        image: windows-latest
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.github\azure-devops\CredScanSuppressions.json
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: "@typescript-eslint/parser"
        parserOptions: ecmaVersion:2018
        enableExclusions: true
        exclusionPatterns: "*.js"
    stages:
      - template: template.yml
        parameters:
          testInstance: true
