# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
trigger: none

pr:
  branches:
    include:
      - main

extends:
  template: pr-template.yml
  parameters:
    repositoryName: 1ESPipelineTemplates/1ESPipelineTemplates
    repositoryRef: refs/tags/stable
    templatePath: v1/1ES.Unofficial.PipelineTemplate.yml
    testInstance: true
