# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased
  - group: PR Metrics

stages:
  - template: template.yml
    parameters:
      testInstance: true

...
