# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: OE/OfficePipelineTemplates
      ref: refs/heads/main

extends:
  template: v1/Office.Unofficial.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        os: windows
        image: windows-latest
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.github\azure-devops\CredScanSuppressions.json
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: '@typescript-eslint/parser'
        parserOptions: ecmaVersion:2018
        enableExclusions: true
        exclusionPatterns: '*.js'
    stages:
      - stage: TEST
        displayName: TEST
        jobs:
          - job: TEST
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              os: linux
              image: ubuntu-latest
            templateContext:
              outputs:
                - output: adoExtension
                  targetPath: $(Build.StagingDirectory)/publish
                  connectedServiceName: PR Metrics
                  fileType: vsix
                  vsixFile: $(Build.StagingDirectory)/publish/ms-omex.PRMetrics.vsix
                  validateExtension: true
            steps:
              - checkout: none
                displayName: Checkout

              - bash: exit 1
                displayName: Terminate on PR
                condition: ne(variables['Build.SourceBranchName'], 'main')

              - task: NodeTool@0
                displayName: Install Node.js
                inputs:
                  versionSpec: 22.x

              - task: Npm@1
                displayName: npm – Install Dependencies
                inputs:
                  command: install

              - task: Npm@1
                displayName: npm – Build
                inputs:
                  command: custom
                  customCommand: run build:release
      - template: template.yml

...
