# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

pool:
  vmImage: ubuntu-latest

stages:
  - template: template.yml
