# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: skipComponentGovernanceDetection
    value: true

jobs:
  - job: PRMetrics_macOS
    displayName: PR Metrics – macOS
    pool:
      vmImage: macOS-latest
    variables:
      - name: System.Debug
        value: true
    steps:
      - task: PRMetrics@1
        displayName: PR Metrics
        env:
          SYSTEM_ACCESSTOKEN: $(GITHUB_PAT)
        inputs:
          FileMatchingPatterns: |
            **/*
            !package-lock.json

  - job: PRMetrics_Ubuntu
    displayName: PR Metrics – Ubuntu
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: System.Debug
        value: true
    steps:
      - task: PRMetrics@1
        displayName: PR Metrics
        env:
          SYSTEM_ACCESSTOKEN: $(GITHUB_PAT)
        inputs:
          FileMatchingPatterns: |
            **/*
            !package-lock.json

  - job: PRMetrics_Windows
    displayName: PR Metrics – Windows
    pool:
      vmImage: windows-latest
    variables:
      - name: System.Debug
        value: true
    steps:
      - task: PRMetrics@1
        displayName: PR Metrics
        env:
          SYSTEM_ACCESSTOKEN: $(GITHUB_PAT)
        inputs:
          FileMatchingPatterns: |
            **/*
            !package-lock.json
