# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: prmetrics@1
    displayName: PR Metrics
    env:
      SECRET_GITHUB_PAT: $(GITHUB_PAT)

