# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
    - repository: M365GPT
      type: git
      name: 1ESPipelineTemplates/M365GPT
      ref: refs/tags/release

extends:
  template: v1/M365.Unofficial.PipelineTemplate.yml@M365GPT
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
        os: windows
        image: windows-latest
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.github\azure-devops\CredScanSuppressions.json
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: "@typescript-eslint/parser"
        parserOptions: ecmaVersion:2018
        enableExclusions: true
        exclusionPatterns: "*.js"
    stages:
      - template: template.yml
