# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

pr:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  displayName: PR Build
  steps:
    - displayName: PR Metrics
      task: prmetrics@1

