# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
extends:
  template: pr-template.yml
  parameters:
    repositoryName: OE/OfficePipelineTemplates
    repositoryRef: refs/heads/main
    templatePath: v1/Office.Unofficial.PipelineTemplate.yml
    testInstance: false
