# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: OE/OfficePipelineTemplates
    ref: refs/heads/main

extends:
  template: v1/Office.Unofficial.PipelineTemplate.yml@OfficePipelineTemplates
  stages:
    - template: template.yml
