# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger: none

pr:
  branches:
    include:
      - main

variables:
  - name: tags
    value: multi-phased

resources:
  repositories:
  - repository: OfficePipelineTemplates
    type: git
    name: OE/OfficePipelineTemplates
    ref: refs/heads/main

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        os: windows
        image: windows-latest
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: '@typescript-eslint/parser'
        parserOptions: ecmaVersion:2018
    stages:
      - template: template.yml
