# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

trigger:
  batch: true
  branches:
    include:
      - main

pr: none

variables:
  - name: tags
    value: production, multi-phased

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Checks
    jobs:
    - job: Checks
      variables:
        - name: skipComponentGovernanceDetection
          value: true
      steps:
        - checkout: none
          displayName: Checkout

        - script: exit 1
          displayName: Terminate on PR
          condition: ne(variables['Build.SourceBranchName'], 'main')

  - template: template.yml
