# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
trigger:
  tags:
    include:
      - v*

pr: none

variables:
  - name: tags
    value: production, multi-phased
  - group: PR Metrics

resources:
  repositories:
    - repository: OfficePipelineTemplates
      type: git
      name: 1ESPipelineTemplates/OfficePipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/Office.Official.PipelineTemplate.yml@OfficePipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        os: windows
        image: windows-latest
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.github\azure-devops\CredScanSuppressions.json
      eslint:
        environmentsEs2017: true
        environmentsMocha: true
        environmentsNode: true
        parser: "@typescript-eslint/parser"
        parserOptions: ecmaVersion:2018
        enableExclusions: true
        exclusionPatterns: "*.js"
    stages:
      - stage: Release
        displayName: Release
        jobs:
          - job: Checks
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              os: linux
              image: ubuntu-latest
            steps:
              - checkout: none
                displayName: Checkout

              - bash: exit 1
                displayName: Terminate on Non-Release
                # Releases are performed on tags, which begin with 'v'.
                condition: not(startsWith(variables['Build.SourceBranchName'], 'v'))

          - job: Release
            pool:
              name: Azure-Pipelines-1ESPT-ExDShared
              os: linux
              image: ubuntu-latest
            steps:
              - checkout: self
                displayName: Checkout

              - task: NodeTool@0
                displayName: Install Node.js
                inputs:
                  versionSpec: 20.16.0

              - task: Npm@1
                displayName: npm – Install Dependencies
                inputs:
                  command: ci

              - task: Npm@1
                displayName: npm – Build Release
                inputs:
                  command: custom
                  customCommand: run build:release

              - task: TfxInstaller@4
                displayName: Release – Install TFX CLI
                inputs:
                  version: v0.x

              - bash: tfx extension create --manifest-globs vss-extension.json --output-path ../ms-omex.PRMetrics.vsix
                displayName: Release – Create
                workingDirectory: $(Build.SourcesDirectory)/release

              - task: EsrpCodeSigning@5
                displayName: ESRP CodeSigning
                inputs:
                  ConnectedServiceName: $($env:CONNECTEDSERVICENAME)
                  AppRegistrationClientId: $($env:APPREGISTRATIONCLIENTID)
                  AppRegistrationTenantId: $($env:APPREGISTRATIONTENANTID)
                  AuthAKVName: $($env:AUTHAKVNAME)
                  AuthCertName: $($env:AUTHSIGNCERTNAME)
                  AuthSignCertName: $($env:AUTHSIGNCERTNAME)
                  FolderPath: $(Build.SourcesDirectory)/release
                  Pattern: "*.vsix"
                  signConfigType: inlineSignParams
                  inlineOperation: |-
                    [
                      {
                        "KeyCode": "CP-500813",
                        "OperationCode": "AdoExtensionSign",
                        "ToolName": "sign",
                        "ToolVersion": "1.0",
                        "Parameters": {}
                      },
                      {
                        "KeyCode": "CP-500813",
                        "OperationCode": "AdoExtensionVerify",
                        "ToolName": "sign",
                        "ToolVersion": "1.0",
                        "Parameters": {}
                      }
                    ]
                  SessionTimeout: 30
                env:
                  CONNECTEDSERVICENAME: $(CODESIGNING-CONNECTEDSERVICENAME)
                  APPREGISTRATIONCLIENTID: $(CODESIGNING-APPREGISTRATIONCLIENTID)
                  APPREGISTRATIONTENANTID: $(CODESIGNING-APPREGISTRATIONTENANTID)
                  AUTHAKVNAME: $(CODESIGNING-AUTHAKVNAME)
                  AUTHCERTNAME: $(CODESIGNING-AUTHCERTNAME)
                  AUTHSIGNCERTNAME: $(CODESIGNING-AUTHSIGNCERTNAME)

              - task: AzureCLI@2
                displayName: Release – Publish
                inputs:
                  azureSubscription: PR Metrics
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: |
                    $AccessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
                    tfx extension publish --service-url https://marketplace.visualstudio.com/ --token $AccessToken --vsix ms-omex.PRMetrics.vsix
