# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
parameters:
  - name: testInstance
    type: boolean
    default: false

  - name: generateLicenses
    type: boolean
    default: false

  - name: forceLicenseGeneration
    type: boolean
    default: false

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Prerequisites
        displayName: Prerequisites
        ${{ if parameters.testInstance }}:
          pool: server
          steps:
            - task: Delay@1
              displayName: Wait for Deployment
              inputs:
                delayForMinutes: 5
        ${{ else }}:
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
            os: linux
            image: ubuntu-latest
          variables:
            - group: PR Metrics
          steps:
            - checkout: self
              displayName: Checkout

            - task: NodeTool@0
              displayName: Install Node.js
              inputs:
                versionSpec: 20.17.0

            - task: Npm@1
              displayName: npm – Install Dependencies
              inputs:
                command: ci

            - task: Npm@1
              displayName: npm – Build Release
              inputs:
                command: custom
                customCommand: run build:release

            - task: TfxInstaller@4
              displayName: Azure DevOps – Install TFX CLI
              inputs:
                version: v0.x

            - task: AzureCLI@2
              displayName: Azure DevOps – Sign-in
              inputs:
                azureSubscription: PR Metrics
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  $AccessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
                  tfx login --service-url https://dev.azure.com/$($env:ADOACCOUNT) --token $AccessToken
              env:
                ADOACCOUNT: $(ADOACCOUNT)

            - bash: tfx build tasks delete --task-id 907d3b28-6b37-4ac7-ac75-9631ee53e512 --no-prompt
              displayName: Azure DevOps – Delete Old Task
              continueOnError: true

            - bash: tfx build tasks upload --task-path release/task --no-prompt
              displayName: Azure DevOps – Deploy

      - job: PRMetrics_Ubuntu
        displayName: PR Metrics – Ubuntu
        dependsOn: Prerequisites
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: linux
          image: ubuntu-latest
        variables:
          - name: System.Debug
            value: true
          - group: PR Metrics
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Classic Personal Access Token (PAT) with the public_repo scope.
              PR_METRICS_ACCESS_TOKEN: $(ADOTOGITHUB)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: PRMetrics_Windows
        displayName: PR Metrics – Windows
        dependsOn: PRMetrics_Ubuntu
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: windows
          image: windows-latest
        variables:
          - name: System.Debug
            value: true
          - group: PR Metrics
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Classic Personal Access Token (PAT) with the public_repo scope.
              PR_METRICS_ACCESS_TOKEN: $(ADOTOGITHUB)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: Validation
        displayName: Validation
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: windows
          image: windows-latest
        ${{ if parameters.generateLicenses }}:
          variables:
            - group: PR Metrics
        steps:
          - ${{ if parameters.generateLicenses }}:
              - checkout: self
                displayName: Checkout
                persistCredentials: true

          - task: ComponentGovernanceComponentDetection@0
            displayName: Component Detection

          - ${{ if parameters.generateLicenses }}:
              - pwsh: |
                  if ('${{ parameters.forceLicenseGeneration }}' -eq 'True')
                  {
                      .github/workflows/support/Update-Licenses.ps1 -Force
                  }
                  else
                  {
                      .github/workflows/support/Update-Licenses.ps1
                  }
                displayName: License – Check State
                name: licenseCheck

              - task: notice@0
                displayName: Generate NOTICE File
                continueOnError: true
                name: noticeTask
                condition: eq(variables['licenseCheck.GENERATE_LICENSES'], 'true')
                inputs:
                  outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
                  outputformat: text

              - pwsh: .github/workflows/support/Test-NoticeResult.ps1
                displayName: License – Check Notice Result
                name: noticeCheck
                condition: eq(variables['licenseCheck.GENERATE_LICENSES'], 'true')
                env:
                  SYSTEM_ACCESSTOKEN: $(System.AccessToken)
                  GITHUB_TOKEN: $(ADOTOGITHUB)

              - pwsh: |
                  Get-Content -Path '$(System.DefaultWorkingDirectory)/obj/NOTICE' |
                      Add-Content -Path '$(Build.SourcesDirectory)/src/LICENSE.txt'
                displayName: License – Append Notices
                condition: >-
                  and(
                    eq(variables['licenseCheck.GENERATE_LICENSES'], 'true'),
                    eq(variables['noticeCheck.NOTICE_OK'], 'true')
                  )

              - pwsh: .github/workflows/support/Push-SignedCommit.ps1
                displayName: Git – Commit & Push (Signed)
                condition: >-
                  and(
                    eq(variables['licenseCheck.GENERATE_LICENSES'], 'true'),
                    eq(variables['noticeCheck.NOTICE_OK'], 'true')
                  )
                env:
                  GITHUB_TOKEN: $(ADOTOGITHUB)

          - task: PoliCheck@2
            displayName: PoliCheck
            inputs:
              targetType: F
              optionsFC: 1
              optionsUEPATH: $(Build.SourcesDirectory)/.github/azure-devops/PoliCheckExclusions.xml

          - task: PublishSecurityAnalysisLogs@3
            displayName: Guardian – Publish Artifacts

          - task: PostAnalysis@2
            displayName: Guardian – Perform Analysis
            inputs:
              GdnBreakPolicyMinSev: Note
              GdnBreakGdnToolGosecSeverity: Default
              GdnBreakPolicy: M365
