# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
parameters:
  - name: testInstance
    type: boolean
    default: false

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Prerequisites
        displayName: Prerequisites
        ${{ if parameters.testInstance }}:
          pool: server
          steps:
            - task: Delay@1
              displayName: Wait for Deployment
              inputs:
                delayForMinutes: 5
        ${{ else }}:
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
            os: linux
            image: ubuntu-latest
          variables:
            - group: PR Metrics
          steps:
            - checkout: self
              displayName: Checkout

            - task: NodeTool@0
              displayName: Install Node.js
              inputs:
                versionSpec: 20.17.0

            - task: Npm@1
              displayName: npm – Install Dependencies
              inputs:
                command: ci

            - task: Npm@1
              displayName: npm – Build Release
              inputs:
                command: custom
                customCommand: run build:release

            - task: TfxInstaller@4
              displayName: Azure DevOps – Install TFX CLI
              inputs:
                version: v0.x

            - task: AzureCLI@2
              displayName: Azure DevOps – Sign-in
              inputs:
                azureSubscription: PR Metrics
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  $AccessToken = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
                  tfx login --service-url https://dev.azure.com/$($env:ADOACCOUNT) --token $AccessToken
              env:
                ADOACCOUNT: $(ADOACCOUNT)

            - bash: tfx build tasks delete --task-id 907d3b28-6b37-4ac7-ac75-9631ee53e512 --no-prompt
              displayName: Azure DevOps – Delete Old Task
              continueOnError: true

            - bash: tfx build tasks upload --task-path release/task --no-prompt
              displayName: Azure DevOps – Deploy

      - job: PRMetrics_Ubuntu
        displayName: PR Metrics – Ubuntu
        dependsOn: Prerequisites
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: linux
          image: ubuntu-latest
        variables:
          - name: System.Debug
            value: true
          - group: PR Metrics
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Classic Personal Access Token (PAT) with the public_repo scope.
              PR_METRICS_ACCESS_TOKEN: $(ADOTOGITHUB)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: PRMetrics_Windows
        displayName: PR Metrics – Windows
        dependsOn: PRMetrics_Ubuntu
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: windows
          image: windows-latest
        variables:
          - name: System.Debug
            value: true
          - group: PR Metrics
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Classic Personal Access Token (PAT) with the public_repo scope.
              PR_METRICS_ACCESS_TOKEN: $(ADOTOGITHUB)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: Validation
        displayName: Validation
        pool:
          name: Azure-Pipelines-1ESPT-ExDShared-StaticIP
          os: windows
          image: windows-latest
        variables:
          - group: PR Metrics
        steps:
          - checkout: self
            displayName: Checkout

          - task: ComponentGovernanceComponentDetection@0
            displayName: Component Detection

          - task: notice@0
            displayName: Generate NOTICE File
            inputs:
              outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
              outputformat: text

          - bash: |
              notice_file="$(System.DefaultWorkingDirectory)/obj/NOTICE"
              if [ ! -f "$notice_file" ]; then
                echo "NOTICE file not found. Skipping."
                exit 0
              fi

              if [ "$BUILD_REASON" = "PullRequest" ]; then
                branch="$PR_SOURCE_BRANCH"
              else
                branch="$SOURCE_BRANCH"
              fi
              branch="${branch#refs/heads/}"

              echo "Target branch: $branch"

              content_base64=$(python3 -c "
              import base64, sys
              with open(sys.argv[1], 'rb') as f:
                  print(base64.b64encode(f.read()).decode())
              " "$notice_file")

              api_url="https://api.github.com/repos/$REPO_NAME/contents/NOTICE.txt"

              response=$(curl -s -w "\n%{http_code}" \
                -H "Authorization: token $GITHUB_PAT" \
                -H "Accept: application/vnd.github.v3+json" \
                "$api_url?ref=$branch")

              http_code=$(echo "$response" | tail -1)
              body=$(echo "$response" | sed '$d')

              echo "GitHub API GET status: $http_code"

              existing_sha=""
              if [ "$http_code" = "200" ]; then
                existing_sha=$(python3 -c "
              import json, sys
              data = json.loads(sys.stdin.read())
              print(data['sha'])
              " <<< "$body")

                echo "Existing file SHA: $existing_sha"

                existing_content=$(python3 -c "
              import json, sys
              data = json.loads(sys.stdin.read())
              print(data['content'].replace('\n', ''))
              " <<< "$body")

                if [ "$content_base64" = "$existing_content" ]; then
                  echo "NOTICE.txt is unchanged (content matches). Skipping commit."
                  exit 0
                fi

                echo "NOTICE.txt has changed. Updating (SHA: $existing_sha)."
              else
                echo "NOTICE.txt does not exist on branch. Creating."
              fi

              echo "$content_base64" | python3 -c "
              import json, sys
              content = sys.stdin.read().strip()
              data = {
                  'message': 'Update NOTICE.txt [skip ci]',
                  'content': content,
                  'branch': sys.argv[1]
              }
              if sys.argv[2]:
                  data['sha'] = sys.argv[2]
              print(json.dumps(data))
              " "$branch" "$existing_sha" | \
              curl -s -X PUT \
                -H "Authorization: token $GITHUB_PAT" \
                -H "Accept: application/vnd.github.v3+json" \
                -d @- \
                "$api_url"

              echo "NOTICE.txt committed successfully."
            displayName: Commit NOTICE File
            continueOnError: true
            condition: ne(variables['ADOTOGITHUB'], '')
            env:
              GITHUB_PAT: $(ADOTOGITHUB)
              BUILD_REASON: $(Build.Reason)
              SOURCE_BRANCH: $(Build.SourceBranch)
              PR_SOURCE_BRANCH: $(System.PullRequest.SourceBranch)
              REPO_NAME: $(Build.Repository.Name)

          - task: PoliCheck@2
            displayName: PoliCheck
            inputs:
              targetType: F
              optionsFC: 1
              optionsUEPATH: $(Build.SourcesDirectory)/.github/azure-devops/PoliCheckExclusions.xml

          - task: PublishSecurityAnalysisLogs@3
            displayName: Guardian – Publish Artifacts

          - task: PostAnalysis@2
            displayName: Guardian – Perform Analysis
            inputs:
              GdnBreakPolicyMinSev: Note
              GdnBreakGdnToolGosecSeverity: Default
              GdnBreakPolicy: M365
