# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

parameters:
  - name: testInstance
    type: boolean
    default: false

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Delay
        displayName: Delay
        pool: server
        steps:
          - task: Delay@1
            displayName: Wait for Deployment
            inputs:
              delayForMinutes: '5'

      - job: PRMetrics_macOS
        displayName: PR Metrics – macOS
        dependsOn: Delay
        pool:
          ${{ if parameters.testInstance }}:
            vmImage: macOS-latest
          ${{ else }}:
            name: Azure Pipelines
            os: macOS
            image: macos-latest
        variables:
          - name: skipComponentGovernanceDetection
            value: true
          - name: System.Debug
            value: true
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Azure DevOps Personal Access Token (PAT) with the Agent Pools (Read & Manage) permission.
              PR_METRICS_ACCESS_TOKEN: $(GITHUB_PAT)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: PRMetrics_Ubuntu
        displayName: PR Metrics – Ubuntu
        dependsOn: PRMetrics_macOS
        pool:
          ${{ if parameters.testInstance }}:
            vmImage: ubuntu-latest
          ${{ else }}:
            name: Azure-Pipelines-1ESPT-ExDShared
            os: linux
            image: ubuntu-latest
        variables:
          - name: skipComponentGovernanceDetection
            value: true
          - name: System.Debug
            value: true
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Azure DevOps Personal Access Token (PAT) with the Agent Pools (Read & Manage) permission.
              PR_METRICS_ACCESS_TOKEN: $(GITHUB_PAT)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

      - job: PRMetrics_Windows
        displayName: PR Metrics – Windows
        dependsOn: PRMetrics_Ubuntu
        pool:
          ${{ if parameters.testInstance }}:
            vmImage: windows-latest
          ${{ else }}:
            name: Azure-Pipelines-1ESPT-ExDShared
            os: windows
            image: windows-latest
        variables:
          - name: skipComponentGovernanceDetection
            value: true
          - name: System.Debug
            value: true
        steps:
          - checkout: self
            displayName: Checkout
            fetchDepth: 0

          - task: PRMetrics@1
            displayName: PR Metrics
            env:
              # Azure DevOps Personal Access Token (PAT) with the Agent Pools (Read & Manage) permission.
              PR_METRICS_ACCESS_TOKEN: $(GITHUB_PAT)
            inputs:
              file-matching-patterns: |
                **/*
                !dist/*
                !package-lock.json

...
