# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger:
  - main
pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: Register
      verbosity: Verbose
      alertWarningLevel: Low
      failOnAlert: true
