# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

env:
  es2017: true
  mocha: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - "!.*"

...
