# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License

---
dirs:
  - /
aliveStatusCodes:
  - 200
  - 206
  - 429
ignorePatterns:
  - pattern: ^https://marketplace.visualstudio.com/manage/publishers/ms-omex$
