# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
name: Git Setup and Push
description: 'Setup Git authentication, create branch, commit and push changes'

inputs:
  version:
    description: 'The version string (e.g., "1.7.6")'
    required: true
  branch_name:
    description: 'The branch name to create'
    required: false
    default: ''
  commit_message:
    description: 'The commit message'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Git – Setup Authentication
      run: gh auth setup-git
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Git – Set Name
      run: git config --global user.name "github-actions[bot]"
      shell: bash

    - name: Git – Set Email
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Git – Set Merge Strategy
      run: git config pull.rebase false
      shell: bash

    - name: Git – Create Branch
      run: |
        if [ -n "${{ inputs.branch_name }}" ]; then
          git checkout -b "${{ inputs.branch_name }}"
        else
          git checkout -b "release/v${{ inputs.version }}"
        fi
      shell: bash

    - name: Git – Add Changed Files
      run: git add -A
      shell: bash

    - name: Git – Commit Changed Files
      run: |
        if [ -n "${{ inputs.commit_message }}" ]; then
          git commit -m "${{ inputs.commit_message }}"
        else
          git commit -m "Release v${{ inputs.version }}"
        fi
      shell: bash

    - name: Git – Push Changed Files
      run: |
        if [ -n "${{ inputs.branch_name }}" ]; then
          git push --set-upstream origin "${{ inputs.branch_name }}"
        else
          git push --set-upstream origin "release/v${{ inputs.version }}"
        fi
      shell: bash
