# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
name: Git Setup & Push
description: Sets up git configuration and pushes changes to a release branch

inputs:
  phase:
    description: Release phase number
    required: true
  version:
    description: Version string for the release
    required: true
  github-token:
    description: GitHub token for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Git – Setup Authentication
      shell: bash
      run: gh auth setup-git
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Git – Set Name
      shell: bash
      run: git config --global user.name "github-actions[bot]"

    - name: Git – Set Email
      shell: bash
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Git – Set Merge Strategy
      shell: bash
      run: git config pull.rebase false

    - name: Git – Create Branch
      shell: bash
      run: git checkout -b "release/v${{ inputs.version }}-phase-${{ inputs.phase }}"

    - name: Git – Add Changed Files
      shell: bash
      run: git add -A

    - name: Git – Commit Changed Files
      shell: bash
      run: git commit -m "Release v${{ inputs.version }}"

    - name: Git – Push Changed Files
      shell: bash
      run: git push --set-upstream origin "release/v${{ inputs.version }}-phase-${{ inputs.phase }}"
