# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
name: Git Setup & Push
description: Sets up git configuration and pushes changes to a release branch

inputs:
  phase:
    description: Release phase number
    required: true
  version:
    description: Version string for the release
    required: true
  commit-token:
    # Fine-grained Personal Access Token (PAT) with the following permissions for microsoft/PR-Metrics:
    # - Read access to Metadata
    # - Read and Write access to Code (aka Contents)
    description: Token for committing changes via the GitHub API
    required: true

runs:
  using: composite
  steps:
    - name: Git – Create Branch
      shell: pwsh
      run: git checkout -b release/v${{ inputs.version }}-phase-${{ inputs.phase }}

    - name: Git – Add Changed Files
      shell: pwsh
      run: git add -A

    - name: Git – Commit & Push (Signed)
      uses: grafana/github-api-commit-action@cb4e7799d2cd77d607acf280ed70a0d03572d8bd # v1.0.0
      with:
        commit-message: Release v${{ inputs.version }}
        create-branch-on-remote: true
        stage-all-files: true
        token: ${{ inputs.commit-token }}

    - name: Git – Sync Local with Remote
      shell: pwsh
      run: |
        git fetch origin release/v${{ inputs.version }}-phase-${{ inputs.phase }}
        git reset --hard origin/release/v${{ inputs.version }}-phase-${{ inputs.phase }}
