# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 9 * * 1
  workflow_dispatch: null

permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
  update-code:
    name: Update Code
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          token: ${{ secrets.PR_METRICS_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.13.0

      - name: npm – Install Dependencies
        run: npm ci

      - name: License – Truncate
        run: .github/workflow-scripts/Update-Licenses.ps1

      - name: License – Generate Third-Party Licenses
        run: npx generate-license-file --input package.json --output third-party-licenses.txt --overwrite --eol lf --ci --no-spinner

      - name: License – Update LICENSE.txt
        run: .github/workflow-scripts/Update-ThirdPartyNotices.ps1

      - name: npm – Lint
        run: npm run lint

      - name: npm – Build Package
        run: npm run build:package

      - if: github.ref_name != 'main'
        name: Git – Add Changed Files
        run: git add -A

      - if: github.ref_name != 'main'
        name: Git – Test for Changes
        id: git-test-for-changes
        run: .github/workflow-scripts/Test-Changes.ps1

      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Commit & Push (Signed)
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          commit-message: "chore: fix linting, update dist folder"
          create-branch-on-remote: true
          stage-all-files: true
          token: ${{ secrets.PR_METRICS_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.13.0

      - name: npm – Install Dependencies
        run: npm ci

      - name: npm – Clean
        run: npm run clean

      - name: npm – Build
        run: npm run build

      - name: npm – Test
        run: npm run test

      - name: Release – Create
        run: npx tfx-cli extension create --manifest-globs vss-extension.json --output-path ../ms-omex.PRMetrics.vsix
        working-directory: ${{ github.workspace }}/release

      - name: Release – Upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: PRMetrics
          path: ${{ github.workspace }}/ms-omex.PRMetrics.vsix

  test-github-action:
    name: Test GitHub Action
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: PR Metrics
        uses: ./
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.PR_METRICS_TOKEN }}
        with:
          file-matching-patterns: |
            **/*
            !dist/*
            !package-lock.json

  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: CodeQL – Initialize
        uses: github/codeql-action/init@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          build-mode: none
          config-file: .github/linters/codeql.yml
          languages: javascript-typescript
          queries: code-quality,code-scanning,security-and-quality,security-experimental,security-extended

      - name: CodeQL – Analyze
        uses: github/codeql-action/analyze@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          category: TypeScript

  validate-linter:
    name: Validate – Linter
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        env:
          FILTER_REGEX_EXCLUDE: .*dist/.*
          FIX_JSON_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_NATURAL_LANGUAGE: true
          FIX_TYPESCRIPT_PRETTIER: true
          FIX_YAML_PRETTIER: true
          GITHUB_TOKEN: ${{ secrets.PR_METRICS_TOKEN }}
          GITLEAKS_CONFIG_FILE: gitleaks.toml
          MARKDOWN_CONFIG_FILE: ../../.markdownlint.json
          # Disable linters that conflict with other linters.
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_JSON: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false

      - if: github.ref_name != 'main'
        name: Git – Test for Changes
        id: git-test-for-changes
        run: .github/workflow-scripts/Test-Changes.ps1

      # Super-Linter must operate on the commit, but changes must be pushed to
      # the branch. To facilitate this, the changes are stashed, the branch is
      # checked out, and the changes are applied back.
      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Stash Changes
        run: git stash --include-untracked

      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Checkout PR Branch
        run: |-
          git fetch origin $Env:HEAD_REF
          git checkout $Env:HEAD_REF
        env:
          HEAD_REF: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Apply Stashed Changes
        run: git stash pop

      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Add Changed Files
        run: git add -A

      - if: github.ref_name != 'main' && steps.git-test-for-changes.outputs.CHANGES_PRESENT == 'True'
        name: Git – Commit & Push (Signed)
        uses: grafana/github-api-commit-action@b1d81091e8480dd11fcea8bc1f0ab977a0376ca5 # v1.0.0
        with:
          commit-message: "chore: fix linting"
          create-branch-on-remote: true
          stage-all-files: true
          token: ${{ secrets.PR_METRICS_TOKEN }}

  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: gh – Log Version
        run: gh --version

      - if: github.actor == 'dependabot[bot]'
        name: Enable Auto-Merge
        run: gh pr merge --auto --delete-branch --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PR_METRICS_TOKEN }}
