# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Deploy

on:
  workflow_dispatch: null

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [PRMetrics]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x

      - name: NPM – Install Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task

      - name: Login
        run: npx tfx login --service-url https://${{ secrets.AZURE_DEVOPS_INSTANCE }}.visualstudio.com/DefaultCollection --token ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }} --no-prompt
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task

      - name: NPM – Deploy
        run: npm run deploy:release
        working-directory: ${{ github.workspace }}/PipelinesTasks/${{ matrix.task }}/src/task
