# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
name: Git Setup & Push

on:
  workflow_call:
    inputs:
      phase:
        required: true
        type: string
      version:
        required: true
        type: string

permissions: {}

jobs:
  git-setup-and-push:
    name: Git Setup & Push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git – Setup Authentication
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git – Set Name
        run: git config --global user.name "github-actions[bot]"

      - name: Git – Set Email
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Git – Set Merge Strategy
        run: git config pull.rebase false

      - name: Git – Create Branch
        run: git checkout -b "release/v${{ inputs.version }}-phase-${{ inputs.phase }}"

      - name: Git – Add Changed Files
        run: git add -A

      - name: Git – Commit Changed Files
        run: git commit -m "Release v${{ inputs.version }}"

      - name: Git – Push Changed Files
        run: git push --set-upstream origin "release/v${{ inputs.version }}-phase-${{ inputs.phase }}"
